# Generated by Django 3.0.2 on 2020-02-09 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionMst',
            fields=[
                ('action', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('inquiry_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry_no', models.ForeignKey(db_column='inquiry_no', on_delete=django.db.models.deletion.CASCADE, to='engine.Inquiry')),
                ('reaction', models.ForeignKey(db_column='reaction', on_delete=django.db.models.deletion.DO_NOTHING, to='engine.ActionMst')),
            ],
        ),
    ]
